bixji/urls.py
# Define urlpatterns in project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("web.urls", namespace="web")),
        path("sitemap.xml", TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml")),
        path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

admin.site.site_header = "PROJECT Administration"
admin.site.site_title = "PROJECT Admin Portal"
admin.site.index_title = "Welcome to PROJECT Admin Portal"

web/urls.py
from django.urls import path
from . import views

app_name = "web"

urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("bixji-talks/", views.bixji_talks, name="bixji_talks"),
    path("magazines/", views.magazines, name="magazines"),
    path("awards/", views.awards, name="awards"),
    path("award-detail/<slug:slug>/", views.award_detail, name="award_detail"),
    path("awards-gallery/", views.award_gallery, name="awards_gallery"),
    path("clubs/", views.clubs, name="clubs"),
    path('club/<slug:slug>/', views.club_detail, name='club_detail'),
    path("events/", views.events, name="events"),
    path('event/<slug:slug>/', views.event_detail, name='event_detail'),
    path("event-gallery/", views.event_gallery, name="event_gallery"),
    path("contact/", views.contact, name="contact")
]

templates/web/partials/footer.html
{% load static %}
<!-- footer-area-start -->
<footer>
    <div class="td-footer-area bg-position pt-130" data-background="{% static 'web/assets/img/footer/bg.jpg' %}">
        <div class="container">
            <div class="row mb-30">
                <!-- Footer Logo & Description -->
                <div class="col-lg-3 col-md-5">
                    <div class="td-footer-widget mb-40">
                        <div class="td-footer-logo mb-20">
                            <a href="{% url 'web:index' %}">
                                <img src="{% static 'web/assets/img/logo/logo-white.png' %}" alt="logo">
                            </a>
                        </div>
                        <p class="text">
                            Bixji connects leaders, creators, and innovators through inspiring talks, exclusive clubs, and engaging events that promote growth, collaboration, and community.
                        </p>
                    </div>
                </div>

                <!-- Quick Links -->
                <div class="col-lg-5 col-md-7">
                    <div class="td-footer-widget space ml-90 mb-40">
                        <h3 class="td-footer-title mb-20">Quick Links</h3>
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="td-footer-links">
                                    <ul>
                                        <li><a href="{% url 'web:index' %}">Home</a></li>
                                        <li><a href="{% url 'web:about' %}">About</a></li>
                                        <li><a href="{% url 'web:bixji_talks' %}">Bixji Talks</a></li>
                                        <li><a href="{% url 'web:magazines' %}">Magazines</a></li>
                                        <li><a href="{% url 'web:awards' %}">Awards</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="td-footer-links">
                                    <ul>
                                        <li><a href="{% url 'web:awards_gallery' %}">Awards Gallery</a></li>
                                        <li><a href="{% url 'web:clubs' %}">Clubs</a></li>
                                        <li><a href="{% url 'web:events' %}">Events</a></li>
                                        <li><a href="{% url 'web:event_gallery' %}">Events Gallery</a></li>
                                        <li><a href="{% url 'web:contact' %}">Contact Us</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Social Media Links -->
                <div class="col-lg-4 col-md-6">
                    <div class="td-footer-widget td-footer-subscribe mb-40">
                        <h3 class="td-footer-title mb-20">Follow Us</h3>
                        <ul class="td-footer-social list-inline">
                            <li class="list-inline-item">
                                <a href="https://www.facebook.com/" target="_blank"><i class="fab fa-facebook-f"></i> Facebook</a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://www.instagram.com/" target="_blank"><i class="fab fa-instagram"></i> Instagram</a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://www.linkedin.com/" target="_blank"><i class="fab fa-linkedin-in"></i> LinkedIn</a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://www.youtube.com/" target="_blank"><i class="fab fa-youtube"></i> YouTube</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="td-footer-bottom pt-40 pb-15">
                        <div class="row align-items-center">
                            <div class="col-md-9">
                                <div class="td-footer-bottom-copyright mb-30">
                                    <p>Copyright {% now 'Y' %}, All Right reserved by <a href="https://bixji.in/" target="_blank"> BIXJI.</a></p>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="td-footer-bottom-social text-right mb-30">
                                    <span><a href="#"><i class="fa-brands fa-linkedin"></i></a></span>
                                    <span><a href="#"><i class="fa-brands fa-instagram"></i></a></span>
                                    <span>
                                        <a href="#">
                                            <svg width="21" height="18" viewBox="0 0 21 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                <path d="M16.3783 0.111328H19.3942L12.8054 7.64181L20.5565 17.8891H14.4875L9.73399 11.6742L4.2949 17.8891H1.27723L8.32453 9.83441L0.888855 0.111328H7.11199L11.4087 5.79201L16.3783 0.111328ZM15.3199 16.084H16.991L6.20396 1.82164H4.41068L15.3199 16.084Z" fill="currentColor" />
                                            </svg>
                                        </a>
                                    </span>
                                    <span><a href="#"><i class="fa-brands fa-whatsapp"></i></a></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- footer-area-end -->

    

templates/web/partials/header.html
{% load static %}
<!-- header-area -->
    <header class="td-header-height">

        <div class="td-header__area z-index-999 td-transparent ">
            <div class="td-header-3-top d-none d-lg-block">
                <div class="container-fluid container-1680">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="td-header-3-top-info">
                                <span><a href="https://maps.app.goo.gl/dwE5HjxV1JEcH15F9"><i class="flaticon-gps"></i>Kondotty, Kerala</a></span>
                                <span class="dvdr">/</span>
                                <span><a href="tel:+919847520679"><i class="flaticon-phone"></i>+91 9847520679</a></span>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="d-none d-lg-block">
                                <div class="td-header-3-top-social d-flex align-items-center justify-content-end">
                                    <span class="td-email"><a href="mailto:info@bixji.com"><i class="flaticon-mail"></i>info@bixji.com</a></span>
                                    <span class="dvdr">/</span>
                                    <span><a href="#"><i class="fa-brands fa-facebook"></i></a></span>
                                    <span>
                                        <a href="#">
                                            <svg width="19" height="19" viewBox="0 0 19 19" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                <path d="M13.8679 1.60596H16.4382L10.8229 8.02398L17.4289 16.7575H12.2564L8.20515 11.4607L3.56956 16.7575H0.997689L7.00391 9.89267L0.666687 1.60596H5.97049L9.6325 6.44745L13.8679 1.60596ZM12.9658 15.219H14.3901L5.1966 3.06361H3.66824L12.9658 15.219Z" fill="currentColor"></path>
                                            </svg>
                                        </a>
                                    </span>
                                    <span><a href="#"><i class="fa-brands fa-linkedin"></i></a></span>
                                    <span><a href="#"><i class="fa-brands fa-instagram"></i></a></span>
                                    <span><a href="#"><i class="fa-brands fa-whatsapp"></i></a></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="header-sticky" class="header-mobile-spacing">
                <div class="container-fluid container-1680">
                    <div class="row align-items-center">
                        <div class="col-xxl-9 col-xl-9 col-6">
                            <div class="tdmenu__wrap d-flex align-items-center justify-content-between">
                                <div class="logo">
                                    <a class="logo-1 logo-sticky-none" href="{% url 'web:index' %}"><img data-width="150" src="{% static 'web/assets/img/logo/logo-white.png' %}" alt="Logo"></a>
                                    <a class="logo-2 d-none" href="{% url 'web:index' %}"><img data-width="150" src="{% static 'web/assets/img/logo/logo-black.png' %}" alt="Logo"></a>
                                </div>
                                <nav class="tdmenu__nav tdmenu-3 ml-50 mr-40 d-none d-xl-flex">
                                    <div class="tdmenu__navbar-wrap tdmenu__main-menu">
                                        <ul class="navigation">
                                            <li class="{% if is_index %}active{% endif %}"><a href="{% url 'web:index' %}">Home</a></li>
                                            <li class="{% if is_about %}active{% endif %}"><a href="{% url 'web:about' %}">About</a></li>
                                            <li class="{% if is_bixji_talks %}active{% endif %}"><a href="{% url 'web:bixji_talks' %}">Bixji Talks</a></li>
                                            <li class="{% if is_magazines %}active{% endif %}"><a href="{% url 'web:magazines' %}">Magazines</a></li>
                                            <li class="menu-item-has-children {% if is_awards %}active{% endif %}"><a href="javascript:void(0)">Awards</a>
                                                <ul class="sub-menu">
                                                    <li><a href="{% url 'web:awards' %}">Awards</a></li>
                                                    <li><a href="{% url 'web:awards_gallery' %}">Awards Gallery</a></li>
                                                </ul>
                                            </li>
                                            <li class="{% if is_clubs %}active{% endif %}"><a href="{% url 'web:clubs' %}">Clubs</a></li>
                                            <li class="menu-item-has-children {% if is_events %}active{% endif %}"><a href="javascript:void(0)">Events</a>
                                                <ul class="sub-menu">
                                                    <li><a href="{% url 'web:events' %}">Events</a></li>
                                                    <li><a href="{% url 'web:event_gallery' %}">Events Gallery</a></li>
                                                </ul>
                                            </li>
                                            <li class="{% if is_contact %}active{% endif %}"><a href="{% url 'web:contact' %}">Contact</a></li>
                                        </ul>
                                    </div>
                                </nav>
                            </div>
                        </div>
                        <div class="col-xxl-3 col-xl-3 col-6">
                            <div class="td-menu-right-action td-menu-right-action-3 d-flex align-items-center justify-content-end">
                                
                                <div class="td-header-menu-bar lh-1 p-relative ml-20">
                                    <a class="td-btn td-left-right d-none d-xl-block" href="{% url 'web:contact' %}">
                                        <span class="mr10 td-text d-inline-block mr-5">Login / Member Dashboard</span>
                                        <span class="td-arrow-angle">
                                            <svg class="td-arrow-svg-top-right" width="13" height="14" viewBox="0 0 13 14" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                <path d="M0.943836 13.5C0.685616 13.5 0.45411 13.4021 0.276027 13.224C0.0979452 13.0459 0 12.8055 0 12.5562C0 12.3068 0.0979452 12.0664 0.276027 11.8884L9.76781 2.38767H2.02123C1.49589 2.38767 1.0774 1.96027 1.0774 1.44384C1.0774 0.927397 1.50479 0.5 2.03014 0.5H12.0562C12.1274 0.5 12.1986 0.508904 12.2788 0.526712L12.4034 0.562329L12.537 0.633562C12.5637 0.65137 12.5993 0.678082 12.626 0.69589C12.6973 0.749315 12.7507 0.80274 12.7952 0.856164C12.8219 0.891781 12.8575 0.927397 12.8842 0.989726L12.9555 1.1411L12.9822 1.22123C13 1.29247 13.0089 1.3726 13.0089 1.44384V11.4699C13.0089 11.9952 12.5815 12.4137 12.0651 12.4137C11.5486 12.4137 11.1212 11.9863 11.1212 11.4699V3.72329L1.62055 13.224C1.44247 13.4021 1.20205 13.5 0.943836 13.5Z" fill="white" />
                                                <path d="M0.943836 13.5C0.685616 13.5 0.45411 13.4021 0.276027 13.224C0.0979452 13.0459 0 12.8055 0 12.5562C0 12.3068 0.0979452 12.0664 0.276027 11.8884L9.76781 2.38767H2.02123C1.49589 2.38767 1.0774 1.96027 1.0774 1.44384C1.0774 0.927397 1.50479 0.5 2.03014 0.5H12.0562C12.1274 0.5 12.1986 0.508904 12.2788 0.526712L12.4034 0.562329L12.537 0.633562C12.5637 0.65137 12.5993 0.678082 12.626 0.69589C12.6973 0.749315 12.7507 0.80274 12.7952 0.856164C12.8219 0.891781 12.8575 0.927397 12.8842 0.989726L12.9555 1.1411L12.9822 1.22123C13 1.29247 13.0089 1.3726 13.0089 1.44384V11.4699C13.0089 11.9952 12.5815 12.4137 12.0651 12.4137C11.5486 12.4137 11.1212 11.9863 11.1212 11.4699V3.72329L1.62055 13.224C1.44247 13.4021 1.20205 13.5 0.943836 13.5Z" fill="white" />
                                            </svg> 
                                        </span>
                                    </a>
                                    <button class="tdmenu-offcanvas-open-btn mobile-nav-toggler d-block d-xl-none">
                                        <span></span>
                                        <span></span>
                                        <span></span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Mobile Menu  -->
        <div class="tdmobile__menu">
            <nav class="tdmobile__menu-box">
                <div class="close-btn"><i class="fa-solid fa-xmark"></i></div>
                <div class="nav-logo">
                    <a href="{% url 'web:index' %}"><img src="{% static 'web/assets/img/logo/logo-black.png' %}" alt="logo"></a>
                </div>
               
                <div class="tdmobile__menu-outer">
                    <!--Here Menu Will Come Automatically Via Javascript / Same Menu as in Header-->
                </div>
                <div class="mt-30 ml-25 mr-25">
                    <a class="td-btn td-left-right w-100 text-center" href="{% url 'web:contact' %}">
                        <span class="mr10 td-text d-inline-block mr-5">Login / Member Dashboard</span>
                        <span class="td-arrow-angle">
                            <svg class="td-arrow-svg-top-right" width="13" height="14" viewBox="0 0 13 14" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M0.943836 13.5C0.685616 13.5 0.45411 13.4021 0.276027 13.224C0.0979452 13.0459 0 12.8055 0 12.5562C0 12.3068 0.0979452 12.0664 0.276027 11.8884L9.76781 2.38767H2.02123C1.49589 2.38767 1.0774 1.96027 1.0774 1.44384C1.0774 0.927397 1.50479 0.5 2.03014 0.5H12.0562C12.1274 0.5 12.1986 0.508904 12.2788 0.526712L12.4034 0.562329L12.537 0.633562C12.5637 0.65137 12.5993 0.678082 12.626 0.69589C12.6973 0.749315 12.7507 0.80274 12.7952 0.856164C12.8219 0.891781 12.8575 0.927397 12.8842 0.989726L12.9555 1.1411L12.9822 1.22123C13 1.29247 13.0089 1.3726 13.0089 1.44384V11.4699C13.0089 11.9952 12.5815 12.4137 12.0651 12.4137C11.5486 12.4137 11.1212 11.9863 11.1212 11.4699V3.72329L1.62055 13.224C1.44247 13.4021 1.20205 13.5 0.943836 13.5Z" fill="white" />
                                <path d="M0.943836 13.5C0.685616 13.5 0.45411 13.4021 0.276027 13.224C0.0979452 13.0459 0 12.8055 0 12.5562C0 12.3068 0.0979452 12.0664 0.276027 11.8884L9.76781 2.38767H2.02123C1.49589 2.38767 1.0774 1.96027 1.0774 1.44384C1.0774 0.927397 1.50479 0.5 2.03014 0.5H12.0562C12.1274 0.5 12.1986 0.508904 12.2788 0.526712L12.4034 0.562329L12.537 0.633562C12.5637 0.65137 12.5993 0.678082 12.626 0.69589C12.6973 0.749315 12.7507 0.80274 12.7952 0.856164C12.8219 0.891781 12.8575 0.927397 12.8842 0.989726L12.9555 1.1411L12.9822 1.22123C13 1.29247 13.0089 1.3726 13.0089 1.44384V11.4699C13.0089 11.9952 12.5815 12.4137 12.0651 12.4137C11.5486 12.4137 11.1212 11.9863 11.1212 11.4699V3.72329L1.62055 13.224C1.44247 13.4021 1.20205 13.5 0.943836 13.5Z" fill="white" />
                            </svg> 
                        </span>
                    </a>
                </div>
                <div class="social-links">
                    <ul class="list-wrap">
                        <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                        <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                        <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                        <li><a href="#"><i class="fab fa-youtube"></i></a></li>
                    </ul>
                </div>
            </nav>
        </div>
        <div class="tdmobile__menu-backdrop"></div>
        <!-- End Mobile Menu -->

        <!-- offCanvas-menu -->
        <div class="offCanvas__info">
            <div class="offCanvas__close-icon menu-close">
                <button><i class="fa-sharp fa-regular fa-xmark"></i></button>
            </div>
            <div class="offCanvas__logo mb-30">
                <a href="{% url 'web:index' %}"><img src="{% static 'web/assets/img/logo/logo-black.png' %}" alt="Logo"></a>
            </div>
            <div class="offCanvas__side-info mb-30">
                <div class="contact-list mb-30">
                    <h4>Office Address</h4>
                    <a href="https://maps.app.goo.gl/dwE5HjxV1JEcH15F9" target="_blank">Kondotty, Kerala</a>
                </div>
                <div class="contact-list mb-30">
                    <h4>Phone Number</h4>
                    <a href="tel:(090)87658654385">+91 9847520679</a>
                </div>
                <div class="contact-list mb-30">
                    <h4>Email Address</h4>
                    <a href="mailto:info@bixji.com">info@bixji.com</a>
                </div>
            </div>
            <div class="offCanvas__social-icon mt-30">
                <a href="javascript:void(0)"><i class="fab fa-facebook-f"></i></a>
                <a href="javascript:void(0)"><i class="fab fa-twitter"></i></a>
                <a href="javascript:void(0)"><i class="fab fa-google-plus-g"></i></a>
                <a href="javascript:void(0)"><i class="fab fa-instagram"></i></a>
            </div>
        </div>
        <div class="offCanvas__overly"></div>
        <!-- offCanvas-menu-end -->

    </header>
    <!-- header-area-end -->